# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-21 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('breed', models.TextField()),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=6)),
                ('weight', models.IntegerField()),
                ('bodyCondition', models.CharField(max_length=128)),
                ('activity', models.CharField(max_length=128)),
                ('image', models.ImageField(default='static/images/dogDefault.png', upload_to='media/cache')),
            ],
        ),
        migrations.CreateModel(
            name='PastFoodDog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petzoapp.Dog')),
            ],
        ),
    ]
