# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-26 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petzoapp', '0003_auto_20170621_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='no_of_referred_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_credit',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referralcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petzoapp.UserProfile'),
        ),
    ]
