# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-27 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petzoapp', '0005_auto_20170626_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='referral',
            new_name='referral_taken',
        ),
    ]
