# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petzoapp', '0008_auto_20170629_0633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Totals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='INR', max_length=5)),
                ('incl_tax', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('excl_tax', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
            ],
        ),
    ]
