# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petzoapp', '0009_totals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcode',
            name='discount_giver',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='discount_taker',
            field=models.FloatField(blank=True),
        ),
    ]
