# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petzoapp', '0012_auto_20170706_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralcode',
            name='discount_giver',
        ),
        migrations.RemoveField(
            model_name='referralcode',
            name='discount_taker',
        ),
    ]
