# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-11 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petzoapp', '0013_auto_20170707_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastfooddog',
            name='dog',
        ),
        migrations.AddField(
            model_name='dog',
            name='pastfood',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.DeleteModel(
            name='PastFoodDog',
        ),
    ]
