# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-11 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petzoapp', '0014_auto_20170711_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='calories',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
    ]
