# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-11 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petzoapp', '0015_dog_calories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='image',
        ),
    ]
