# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-11 13:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('petzoapp', '0016_remove_dog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('breed', models.TextField()),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=6)),
                ('neutered', models.BooleanField(default=False)),
                ('pregnant', models.BooleanField(default=False)),
                ('pregMonths', models.IntegerField(default=0)),
                ('lactation', models.BooleanField(default=False)),
                ('number_of_puppies', models.IntegerField(default=0)),
                ('weight', models.IntegerField()),
                ('bodyCondition', models.CharField(max_length=128)),
                ('activity', models.CharField(max_length=128)),
                ('pastfood', models.CharField(blank=True, max_length=128)),
                ('calories', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dog',
            name='lactation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dog',
            name='neutered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dog',
            name='number_of_puppies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dog',
            name='pregMonths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dog',
            name='pregnant',
            field=models.BooleanField(default=False),
        ),
    ]
