# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-13 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petzoapp', '0018_dog_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='pet',
            field=models.CharField(default='dog', max_length=3),
            preserve_default=False,
        ),
    ]
