# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-15 14:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('petzoapp', '0019_cat_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('code', models.CharField(blank=True, max_length=128)),
                ('address', models.TextField(blank=True)),
                ('no_of_referred_users', models.IntegerField(default=0)),
                ('user_credit', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vet',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
