# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-15 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petzoapp', '0020_auto_20170715_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='code',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
    ]
