# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-16 05:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('petzoapp', '0021_auto_20170715_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='vet_update',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 16, 5, 51, 56, 140623, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
