# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-17 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petzoapp', '0022_userprofile_vet_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=128, unique=True)),
                ('order_id', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupplementsInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=128, unique=True)),
                ('order_id', models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
